name: npc_mobile_flutter
description: Cross-platform mobile app for browsing and displaying product information.

# Specify the location to publish the package. 'none' means it won't be published to pub.dev.
publish_to: 'none'

# The version number of the Flutter project.
version: 1.3.1+32

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #for launching url
  url_launcher: ^6.2.1

  #For scanning QR code and barcode
  mobile_scanner: ^5.1.1
  image_picker: ^1.0.4

  #For accessing environment variables
  flutter_dotenv: ^5.1.0

  #For making api calls
  akeneo_api_client: ^1.0.4

  #For loading animation
  flutter_spinkit: ^5.2.0

  #For displaying images
  cached_network_image: ^3.3.0

  #For parsing Gs1 barcodes
  gs1_barcode_parser: ^1.0.5

  #For formatting dates
  intl: ^0.19.0

  #For getting the version of the app
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting rules for maintaining code quality.
  flutter_lints: ^4.0.0

  #For changing app package name
  change_app_package_name: ^1.1.0 # dart run change_app_package_name:main com.etdvlpr.npc_mobile_flutter

  #For changing app icon
  flutter_launcher_icons: ^0.13.1 # dart run flutter_launcher_icons

  #For creating splash screen
  flutter_native_splash: ^2.3.2 # dart run flutter_native_splash:create

# Flutter specific configuration.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png

  android_12:
    image: assets/images/12/splash.png
    color: "#ffffff"
    icon_background_color: "#ffffff"

  android: true
  ios: true

  android_gravity: center
  ios_content_mode: center

  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
